# Edit this Gemfile to bundle your application's dependencies.
# This preamble is the current preamble for Rails 3 apps; edit as needed.
source 'http://rubygems.org'

gem 'rails', '3.0.9'

gem 'ancestry', '>=1.2.0'
gem 'Empact-authlogic', '>=2.1.5', :require => 'authlogic'
gem 'Empact-authlogic_rpx', '>= 1.1.8', :require => 'authlogic_rpx'
gem 'bluecloth', '>=2.0.5'
gem 'declarative_authorization'
gem 'delayed_job', '>= 2.0.3'
gem 'erubis', '>= 2.6.6'
gem 'excelsior'
gem 'fastercsv'
gem 'foreigner'
gem 'friendly_id', '>= 3.0.6'
gem 'geokit'
gem 'gravtastic', '= 3.1.0'
gem 'hoptoad_notifier', '>= 2.3.2'
gem 'jammit', '>= 0.5.3'
gem 'json', '>= 1.4.3'
gem 'loofah'
gem 'puppet', '>= 2.6.0'
gem 'bson_ext'
gem 'mongo_mapper'
gem 'mongo_session_store'
gem 'newrelic_rpm', '>= 2.12.3'
gem 'nokogiri'
gem 'paperclip', '>= 2.3.3'
gem 'pg'
gem 'rpx_now', '>= 0.6.12'
gem 'Empact-sexy_pg_constraints', require: 'sexy_pg_constraints'
gem 'state_machine'
gem 'spatial_adapter'
gem 'sunspot_rails'
gem 'polly-suppress_validations', :require => 'suppress_validations'
gem 'tamtam'
gem 'typhoeus'
gem 'votesmart', '>= 0.3.3'
gem 'kaminari'
gem 'ym4r'
gem 'httparty'
gem 'parallel'

group :test, :development do
  gem "rspec-rails"
end
