# Edit this Gemfile to bundle your application's dependencies.
# This preamble is the current preamble for Rails 3 apps; edit as needed.
source 'http://rubygems.org'

gem 'rails', '3.1.0.rc5'

gem 'ancestry', '>=1.2.0'
gem 'Empact-authlogic', '>=3.0.3', :require => 'authlogic'
gem 'Empact-authlogic_rpx', '>= 1.1.8', :require => 'authlogic_rpx'
gem 'bluecloth', '>=2.0.5'
gem 'declarative_authorization'
gem 'delayed_job', '>= 2.0.3'
gem 'erubis', '>= 2.6.6'
gem 'excelsior'
gem 'fastercsv'
gem 'foreigner'
gem 'friendly_id', '>= 3.0.6'
gem 'geokit'
gem 'gravtastic', '= 3.1.0'
gem 'hoptoad_notifier', '>= 2.3.2'
gem 'jammit', '>= 0.5.3'
gem 'loofah'
gem 'bson_ext'
gem 'mongo_mapper'
gem 'mongo_session_store'
gem 'newrelic_rpm', '>= 2.12.3'
gem 'nokogiri'
gem 'paperclip', '>= 2.3.3'
gem 'pg'
gem 'rpx_now', '>= 0.6.12'
gem 'Empact-sexy_pg_constraints', require: 'sexy_pg_constraints'
gem 'state_machine'
gem 'spatial_adapter'
gem 'sunspot_rails'
gem 'tamtam'
gem 'typhoeus'
gem 'votesmart', '>= 0.3.3'
gem 'kaminari'
gem 'ym4r'
gem 'httparty'
gem 'parallel'
gem 'shadow_puppet', git: 'git://github.com/railsmachine/shadow_puppet.git', branch: '1.9'

group :test, :development do
  gem 'thin'
  gem "rspec-rails"
  gem 'fixjour'
  gem 'fakeweb'
  gem 'forgery'
  gem 'rr'
  gem 'parallel'
  gem 'ruby-debug19', require: 'ruby-debug'
end
